### ISSUE TITLE
Missing classes F38 & F50

### ISSUE THREAD

**Issue by pierrechoffe** [erlangen-crm/efrbroo#1]
Hello,

We are working on a new ontology for music called [DOREMUS](https://github.com/DOREMUS-ANR/doremus-ontology) extending CIDOC CRM and FRBRoo.
We import ecrm: http://erlangen-crm.org/current/
and efrbroo: http://erlangen-crm.org/efrbroo/

We noticed that in our efrbroo import two classes are missing : F38_Characters and F50_Controlled_Access_Point

Can you be so kind as to check this?
Thank you very much in advance,
With all very best wishes,
Pierre Choffé

**Comment by mnscholz** [comment]
The latest file now contains these classes
